# Generated by Django 3.2.6 on 2021-09-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210917_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
