# Generated by Django 3.2.6 on 2021-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20210917_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/Hackathon/static/nopic.jpg', upload_to='images'),
        ),
    ]
