# Generated by Django 3.2.6 on 2021-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/nopic.jpg', upload_to='images'),
        ),
    ]
