# Generated by Django 3.2.6 on 2021-09-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_rename_image_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
