# Generated by Django 3.2.6 on 2021-09-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
