# Generated by Django 3.2.6 on 2021-09-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
