# Generated by Django 3.2.6 on 2021-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210915_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Retailer',
            field=models.BooleanField(),
        ),
    ]
